target(instalacja bibliotek):
    pip install –r requirements.txt
test:
pytest test.py
run: test
flask run

target(uruchomienie flaskrun):
     python –m flask run
test:
pytest test.py
run: test
flask run